### ISSUE TITLE
Tracking issue for authoring of Threats and Controls

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/ai-governance-framework#14]
We need to start dividing up the work, authoring the various Threats / Controls. We'll use this issue to manage that work and their assignments. 

Each threat / control is 'ticked' when assigned to an individual, and ~struck out~ when completed, in Draft form.

**Please add a comment if you would like to pick up one of these threats or controls**

Threats
 - [x]  ~TR-1	Information Leaked to Hosted Model @torinvdb~ https://github.com/finos/ai-readiness/pull/36
 - [x]  ~TR-2	Insufficient access control with vector store @torinvdb~ https://github.com/finos/ai-readiness/pull/37
 - [x]  ~TR-3	Lack of data access controls~ https://github.com/finos/ai-readiness/pull/41
 - [x]  ~TR-4	Hallucination @ColinEberhardt~
 - [x]  ~TR-5	Instability in foundation model behaviour~https://github.com/finos/ai-readiness/pull/41
 - [x]  ~TR-6	Non-deterministic behaviour @nbrown-ScottLogic~ https://github.com/finos/ai-readiness/pull/38
 - [x]  ~TR-7	Availability of foundational @alvin-c-shih~ model https://github.com/finos/ai-readiness/pull/42
 - [x]  ~TR-8	Tampering with the foundational model @aateeque~ https://github.com/finos/ai-readiness/pull/39
 - [x]  ~TR-9	Tampering with the vector store @aateeque~ https://github.com/finos/ai-readiness/pull/39
 - [x]  ~TR-10	Prompt injection @chamindra~ https://github.com/finos/ai-readiness/pull/35
 - [x]  ~TR-11	Lack of foundation model versioning @gibsonlam~  https://github.com/finos/ai-readiness/pull/40
 - [x] finos/ai-governance-framework#8
 - [x] finos/ai-governance-framework#7
 - [x] ~TR-14 Inadequate system alignment~ https://github.com/finos/ai-readiness/pull/55
 - [ ] - TR-15 Loss of Control

Controls
 - [x]  ~CT-1	Data leakage canaries/fingerprint @torinvdb~ https://github.com/finos/ai-readiness/pull/36
 - [x]  ~CT-2	Data filtering from Confluence into the samples @torinvdb~ https://github.com/finos/ai-readiness/pull/37
 - [x]  ~CT-3	User/app/model firewalling/filtering~ https://github.com/finos/ai-readiness/pull/55
 - [ ]  CT-4	System observability 
 - [x]  ~CT-5	System acceptance testing @ColinEberhardt~ 
 - [x]  CT-6	Data quality & classification/sensitivity @i8labs @victorjunlu
 - [ ]  CT-7	Legal/contractual agreements
 - [ ] finos/ai-governance-framework#6
 - [ ]  CT-9	Alerting / DoW spend alert
 - [x]  ~CT-10	Version (pinning) of the foundational model @gibsonlam~ https://github.com/finos/ai-readiness/pull/40
 - [x]  ~CT-11	Human feedback loop~ https://github.com/finos/ai-readiness/pull/57
 - [x]  CT-12	Role-based data access @erebus27011841 @victorjunlu
 - [ ]  CT-13	Provide citations
 - [x]  ~CT-14	Encrypt data at rest @nbrown-ScottLogic and @gkocak-scottlogic~ 
 - [x] ~CT-15 LLM-as-a-Judge @nbrown-ScottLogic~
 - [x] ~CT-16 Preserving access controls in the ingested data~ https://github.com/finos/ai-readiness/pull/41

**Comment by ColinEberhardt** [comment]
superseded by https://github.com/finos/ai-governance-framework/issues/12
